### ISSUE TITLE
Downloading Transactions

### ISSUE THREAD

**Issue by torchtarget** [tducret/revolut-python#2]
Hi, 
Nice tool. 
It would be awesome to download historic transactions.  How did you discover the API urls?
Kind regards
Christian

**Comment by tducret** [comment]
Hi Christian, and thank you.
Downloading transactions is definitely doable. I just didn't need it.
I used Charles proxy and my smartphone to discover Revolut API.
I'll have a look at transactions. Any specific requirements ?


Le lun. 20 août 2018 16:41, Christian B, <notifications@github.com> a
écrit :

**Comment by leikoilja** [comment]
@tducret, how is it going with plans on pulling the transactions? I love the idea and would highly appreciate that functionality. 
I'd be honored to help you with that, if you wouldn't mind?

**Comment by tducret** [comment]
I didn't dig into it yet. Do you think about a specific implementation?
Is it interesting to add this feature in the CLI tool for example?

**Comment by leikoilja** [comment]
@tducret, I was exploring it yesterday with Charles and was able to successfully pull down the transaction history for a specific time period, exiting! I think i ll add it to CLI tool with a parameter to specify `from`(how far in a past) you want to fetch data from. And then just return a `json` data to the user. What do you think about it?

**Comment by tducret** [comment]
Yep! Sounds good to me. Feel free to submit a PR ;)

**Comment by zlymeda** [comment]
Hi @leikoilja , 
if you can provide requests needed to get trxs from revolut, I'd be happy to implement it. Unfortunately charles-proxu does not help me, as I have android 8 and it does not respect user certificates by default.

Thanks

**Comment by zlymeda** [comment]
@leikoilja thanks for the info.

Is there something in headers as well?

I tried this:

```python
> ret = self.client.doGet(_URL_GET_ACCOUNTS)
> data = ret.json()
> wallet_id = data['id']

> TRX_URL = "https://api.revolut.com/user/current/transactions?from=1571335685&walletId={}".format(wallet_id)

> ret = self.client.doGet(TRX_URL)

ConnectionError: Status code 500 for url https://api.revolut.com/user/current/transactions?from=1571335685&walletId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
{"message":"Something went wrong"}
```

I also tried the pocket ID as wallet_id, but that is probably not correct as I got :
403: You have no permission to perform this operation

**Comment by leikoilja** [comment]
@zlymeda, here you go, mate: 
```
import json
import click
from revolut import Revolut


_CLI_DEVICE_ID = 'revolut_cli'
_URL_GET_TRANSACTIONS = 'https://api.revolut.com/user/current/transactions'


@click.command()
@click.option(
    '--token', '-t',
    envvar="REVOLUT_TOKEN",
    type=str,
    help='your Revolut token (or set the env var REVOLUT_TOKEN)',
)
def main(token):
    if token is None:
        print("You don't seem to have a Revolut token")
        sys.exit()

    rev = Revolut(device_id=_CLI_DEVICE_ID, token=token)
    wallet_id = json.loads(
        rev.client._get(
            'https://api.revolut.com/user/current/wallet'
        ).text
    ).get('id')
    transactions = json.loads(
        rev.client._get(
            _URL_GET_TRANSACTIONS + '?from=1571335685&walletId={}'.format(
                wallet_id
            )
        ).text
    )
    print(transactions)


if __name__ == "__main__":
    main()

```
So you can run it as:
`python3 SCRIPT-ABOVE.py --token=XXX`
That's just a quick sketch, more as a concept proof. Feel free to integrate it with `revolut-python` and open a nice PR :+1: 
Ping me please, if you will. Just want to stay in a loop :smile:
