### ISSUE TITLE
How can I use a unique X-Device-Id?

### ISSUE THREAD

**Issue by Breitei** [tducret/revolut-python#21]
We used this Revolut API for many users and after that the accounts of our users get locked, because Revolut thought there was a DDoS attack because every user had the same X-Device-Id.
Do you know how to generate a unique device id that is accepted by the API?

**Comment by tducret** [comment]
Hello @Breitei 
Sorry to hear that. After investigation, it appears that this device id is free, so we can use any string.
In `revolut-emergency` project, they use a unique machine id (see [here](https://github.com/Annihil/revolut-emergency/blob/master/src/api.ts#L6)).
I followed the same logic in PR #22 (and used `uuid.getnode()`).
You can install this version (`pip install revolut==0.1.4.dev1`) to give it a try.
Let me know if that sounds right for you.

**Comment by tducret** [comment]
Should be solved in version `0.1.4`
Please give it a try by upgrading: `pip install revolut==0.1.4`
