### ISSUE TITLE
Token generation with a third factor authentication (selfie) is not currently supported by this package'

### ISSUE THREAD

**Issue by TheYellowKrato** [tducret/revolut-python#23]
Hi,

FIrst time trying your project, I got :
'Token generation with a third factor authentication (selfie) is not currently supported by this package'
When trying to generate a token with cli

**Comment by tducret** [comment]
Hi @TheYellowKrato 
Yep, third factor authentication is not supported yet (since it involves taking a selfie).
See #19 for latest details.
