### ISSUE TITLE
History file missing

### ISSUE THREAD

**Issue by digiajay** [tducret/revolut-python#8]
Hi.. Great work.!

I could generate my token and see my current balances using CLI.  However, I couldn't run the bot.  I'm getting historyfile missing error
```
Usage: revolutbot.py [OPTIONS]
Try "revolutbot.py --help" for help.

Error: Missing option "--historyfile" / "-f".
```

Thanks,
Ajay

**Comment by mehdichaouch** [comment]
Hello @digiajay 

History file sample is root of repository : https://github.com/tducret/revolut-python/blob/master/exchange_history_example.csv

Have a nice day,

**Comment by tducret** [comment]
Thakns @mehdichaouch
